### ISSUE TITLE
Created Date is reset

### ISSUE THREAD

**Issue by lukasvan3l** [Q42/meteor-mind-meld#3]
When I import a collection, all the created dates are reset due to `Collection2` or `collection-hooks` that are also in my project.

**Comment by remcoder** [comment]
I suggest not to fix this as it is a logical result from the method used. If you want to preserve such data you should resort to a more low-level method like dumping/restoring collections via the mongo tools.

**Comment by remcoder** [comment]
running hooks should be an option
